CUDNN_BENCHMARK: false
DATALOADER:
  NAIVE_WAY: true
  NUM_INSTANCE: 4
  NUM_WORKERS: 8
  PK_SAMPLER: true
DATASETS:
  COMBINEALL: false
  NAMES:
  - DukeMTMC
  TESTS:
  - DukeMTMC
INPUT:
  CJ:
    BRIGHTNESS: 0.15
    CONTRAST: 0.15
    ENABLED: false
    HUE: 0.1
    PROB: 0.8
    SATURATION: 0.1
  DO_AUGMIX: false
  DO_AUTOAUG: false
  DO_FLIP: true
  DO_PAD: true
  FLIP_PROB: 0.5
  PADDING: 10
  PADDING_MODE: constant
  REA:
    ENABLED: true
    MEAN:
    - 123.675
    - 116.28
    - 103.53
    PROB: 0.5
  RPT:
    ENABLED: false
    PROB: 0.5
  SIZE_TEST:
  - 128
  - 64
  SIZE_TRAIN:
  - 128
  - 64
MODEL:
  BACKBONE:
    DEPTH: 50x
    LAST_STRIDE: 1
    NAME: build_darknet_backbone
    NORM: BN
    NORM_SPLIT: 1
    PRETRAIN: true
    PRETRAIN_PATH: ''
    WITH_IBN: false
    WITH_NL: false
    WITH_SE: false
  DEVICE: cuda:0
  FREEZE_LAYERS:
  - ''
  HEADS:
    CLS_LAYER: circleSoftmax
    IN_FEAT: 512
    MARGIN: 0.25
    NAME: BNneckHead
    NECK_FEAT: before
    NORM: BN
    NORM_SPLIT: 1
    NUM_CLASSES: 0
    POOL_LAYER: avgpool
    REDUCTION_DIM: 512
    SCALE: 128
  LOSSES:
    CE:
      ALPHA: 0.2
      EPSILON: 0.1
      SCALE: 1.0
    CIRCLE:
      ALPHA: 128
      MARGIN: 0.25
      SCALE: 1.0
    FL:
      ALPHA: 0.25
      GAMMA: 2
      SCALE: 1.0
    NAME:
    - CrossEntropyLoss
    - TripletLoss
    TRI:
      HARD_MINING: true
      MARGIN: 0.3
      NORM_FEAT: false
      SCALE: 1.0
  META_ARCHITECTURE: Baseline
  PIXEL_MEAN:
  - 123.675
  - 116.28
  - 103.53
  PIXEL_STD:
  - 58.395
  - 57.120000000000005
  - 57.375
  WEIGHTS: ''
OUTPUT_DIR: logs/dukemtmc/darknet
SOLVER:
  BASE_LR: 0.02
  BIAS_LR_FACTOR: 2.0
  CHECKPOINT_PERIOD: 30
  DELAY_ITERS: 0
  ETA_MIN_LR: 0.001
  FREEZE_ITERS: 0
  GAMMA: 0.1
  HEADS_LR_FACTOR: 1.0
  IMS_PER_BATCH: 64
  MAX_ITER: 320
  MOMENTUM: 0.9
  OPT: SGD
  SCHED: WarmupMultiStepLR
  STEPS:
  - 35
  - 65
  SWA:
    ENABLED: false
    ETA_MIN_LR: 3.5e-06
    ITER: 10
    LR_FACTOR: 10.0
    LR_SCHED: false
    PERIOD: 2
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 15
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
TEST:
  AQE:
    ALPHA: 3.0
    ENABLED: false
    QE_K: 5
    QE_TIME: 1
  EVAL_PERIOD: 30
  IMS_PER_BATCH: 128
  METRIC: cosine
  PRECISE_BN:
    DATASET: Market1501
    ENABLED: false
    NUM_ITER: 300
  RERANK:
    ENABLED: false
    K1: 20
    K2: 6
    LAMBDA: 0.3
